name: typecraft
description: Elegant & Intuitive app to help you type faster...
publish_to: "none"
version: 2.0.0
repository: https://github.com/aldrinmathew/typecraft

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  trex: ^1.1.0
  # msix: ^2.4.2
  flutter_svg: ^0.23.0+1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  animated_flip_counter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

  # msix_config:
  #   display_name: Typecraft
  #   publisher_display_name: Aldrin's Art Factory
  #   identity_name: aldrinsartfactory.utility.typecraft
  #   msix_version: 2.2.0.2
  #   logo_path:

  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages